# Generated by Django 3.0.3 on 2020-03-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='book',
            name='callnumber',
            field=models.CharField(help_text='3-digit <a href="https://www.library.illinois.edu/infosci/research/guides/dewey>Call Number</a>', max_length=3, verbose_name='Call Number'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.TextField(help_text='Enter a brief review of the book', max_length=1000, verbose_name='Review'),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
