# Generated by Django 3.0.4 on 2020-04-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
