# Generated by Django 3.0.3 on 2020-05-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200412_1253'),
        ('catalog', '0003_auto_20200405_1834'),
    ]

    operations = [
    ]
